[package]
name = "meshi-ffi-structs"
version = "0.1.0"
edition = "2021"

[dependencies]
glam = { version = "0.29.2", features = ["bytemuck"] }
winit = "0.26"

[dependencies.bitflags]
version = "2.10.0"
